### ISSUE TITLE
How to

### ISSUE THREAD

**Issue by kratess** [games647/LambdaAttack#24]
Can you make a .jar for library or can you write a installation guide for windows with intellij?

**Comment by games647** [comment]
Because IntelliJ manages the dependencies in a shared manner, it won't detect the relocation of the package structure correctly. You could work around this by opening each sub project indivuallily. So you follow the guide from the README and then open the file core/pom.xml within IntelliJ. That works.

**Comment by kratess** [comment]
Why do you not make a .jar. Then how i import the maven?

**Comment by games647** [comment]
>Why do you not make a .jar.

Because the project is designed to be standalone, but you could make a pull request if you want to.

>Then how i import the maven?

Use the import feature of IntelliJ

**Comment by kratess** [comment]
Can you help me? Where is the import section?

**Comment by games647** [comment]
Just take a carefully at the start screen.

**Comment by kratess** [comment]
Okay... I'll test it
