### ISSUE TITLE
[Question] Can anyone give me some WORKING proxy?

### ISSUE THREAD

**Issue by timof121** [games647/LambdaAttack#46]
Hello, i was checking for security my server but i need a working proxy because the txt that i donwloaded from here: socks-proxy.net,  but it just says timed out and shows a socks error.
Thanks in advanced

**Comment by lukemagdalin** [comment]
these ones currently work for me
198.199.120.102:1080
162.243.108.129:1080
191.96.42.80:1080
104.198.155.18:1080
198.11.179.15:8080
85.13.225.76:65111
85.13.225.75:37451
85.13.226.184:49597
85.13.233.142:61981
138.68.60.8:1080
79.137.95.25:40831
176.9.119.170:1080
138.201.142.30:1080
80.82.69.126:8975
81.17.20.50:17127
95.217.179.149:1080
181.129.7.202:6699
142.93.170.92:1080
78.46.200.216:38816
95.84.164.56:1090
104.236.26.27:38801
98.143.145.30:62353
77.72.138.108:8080
104.248.63.17:30588
104.248.63.49:30588
96.44.133.110:58690
95.0.66.118:6699
174.76.48.228:4145
98.143.145.29:62354
104.248.63.18:30588
116.203.128.117:9050
88.135.39.145:23105
87.241.90.113:10200
93.113.227.4:1080
47.244.17.134:1080

after a quick 5-second google search, I found them here(Make sure they are socks5): http://free-proxy.cz/en/
next time do a google search instead of opening an issue.

**Comment by timof121** [comment]
ok thx
