### ISSUE TITLE
Namelist

### ISSUE THREAD

**Issue by OfficialAName** [games647/LambdaAttack#5]
Would you add nicknames support like "RANDOM, FAKE, NORMAL" and by normal i mean "kermit, xdproxd" and so on.. and proxy list download? like deathbot? and how many threads we can use too?

**Comment by games647** [comment]
I think I would add a way to select a file of names. Otherwise complete random using the name format gui component.

Example format: %rnd{length} for complete random
or format: Bot-%rnd specific prefix

>and proxy list download

Yes that's possible although many SOCKS4/5 proxies goes often down. 

>and how many threads we can use too?

How many concurrent connections your network card can hold.

**Comment by OfficialAName** [comment]
ok, thx :+1:

**Comment by games647** [comment]
Should the namelist be rotating?
